import rondon from "@/assets/enamel-rondon.png";
import finance from "@/assets/enamel-finance.png";
import toninhathon from "@/assets/enamel-toninhathon.png";
import data from "@/assets/enamel-data.png";
import sql from "@/assets/enamel-sql.png";
import health from "@/assets/enamel-health.png";
import type { BadgeGeneratorOutput } from "./badges";

export const demoTrophies: Record<string, BadgeGeneratorOutput & { image: string }> = {
  "projeto-rondon": { badge_name: "IMPACT IN ACTION", badge_subtitle: "120+ young people reached", badge_description: "Created and delivered educational workshops combining culture, citizenship and technology, including an activity reaching more than 120 young people.", achievement_category: "education", visual_prompt: "Die-cut oval enamel pin: Amazon river sunset with açaí palm and canoe, gold lines, \"AMAPÁ 2022\" tab and \"PROJETO RONDON\" ribbon.", icon: "award", image: rondon },
  "liga-financeira": { badge_name: "MARKET MIND", badge_subtitle: "From member to contributor", badge_description: "Joined the PUCRS financial market league and contributed through study groups and written content.", achievement_category: "education", visual_prompt: "Die-cut bull head enamel pin in navy and gold with a green nose ring and a \"PUCRS FINANCE\" ribbon.", icon: "study", image: finance },
  toninhathon: { badge_name: "BUILT TO WIN", badge_subtitle: "Winner · Incubated by SEBRAE", badge_description: "Developed a viable project, won the competition and moved the project forward into incubation.", achievement_category: "career", visual_prompt: "Round silver enamel pin with a toninha leaping out of the frame over blue waves and a \"SALVATON · WINNER\" ribbon.", icon: "ship", image: toninhathon },
  "pratham-books": { badge_name: "DATA FOR MILLIONS", badge_subtitle: "Engineering at meaningful scale", badge_description: "Earned selection, developed a data engineering solution for a large-scale use case and presented the resulting case.", achievement_category: "skills", visual_prompt: "Die-cut open book enamel pin with a rainbow bar chart rising from the pages and a \"STORYWEAVER\" tag.", icon: "study", image: data },
  detectivesql: { badge_name: "CASE CLOSED", badge_subtitle: "Built because it should exist", badge_description: "Created and released detectiveSQL, turning SQL practice into an interactive investigation experience and sharing it publicly.", achievement_category: "creative", visual_prompt: "Die-cut magnifying glass enamel pin: gold fingerprint under a crescent moon, red \"CASE CLOSED\" stamp, wooden handle.", icon: "ship", image: sql },
  "torneio-empreendedor": { badge_name: "FROM PROBLEM TO PRODUCT", badge_subtitle: "Validated · Built · Won", badge_description: "Created a healthcare-focused idea, validated it with a domain specialist, developed the application with AGES and successfully competed through the tournament.", achievement_category: "career", visual_prompt: "Die-cut blue puzzle piece enamel pin with a pink heart, starry sky and a \"MEU MUNDO AZUL\" ribbon.", icon: "ship", image: health },
};