import type { ActivityEvent, Commitment } from "./types";

export const DEMO_USER = { name: "Alex", email: "alex@proof.app", timezone: "America/Sao_Paulo", currency: "USD" };

export const demoCommitments: Commitment[] = [
  {
    id: "run-100",
    title: "Run 100 km in October",
    measurableGoal: "Complete at least 100 km of running between Oct 1 and Oct 31, 2026.",
    status: "active",
    createdAt: "2026-10-01T09:00:00Z",
    lockedAt: "2026-10-01T09:04:00Z",
    deadline: "2026-10-31T23:59:00Z",
    stake: 100,
    currency: "USD",
    failureDestination: "Donate to GiveDirectly",
    methods: ["data", "referee"],
    providers: ["strava"],
    referee: { name: "Maya Chen", email: "maya@example.com", token: "rf_7Kq2mX9pLs", status: "pending" },
    headline: { current: 72, target: 100, unit: "km" },
    criteria: [
      { id: "r1", description: "Run at least 100 km total during October", target: 100, current: 72, unit: "km", status: "progress" },
      { id: "r2", description: "Activities recorded via Strava with GPS", status: "met" },
    ],
    evidence: [],
    runs: [],
  },
  {
    id: "portfolio",
    title: "Ship my portfolio",
    measurableGoal: "Publish a working portfolio website with its source on GitHub by October 31, 2026.",
    status: "active",
    createdAt: "2026-10-07T14:00:00Z",
    lockedAt: "2026-10-07T14:12:00Z",
    deadline: "2026-10-31T23:59:00Z",
    stake: 150,
    currency: "USD",
    failureDestination: "Send to a friend — Jordan",
    methods: ["ai", "data"],
    providers: ["github"],
    criteria: [
      { id: "p1", description: "GitHub repository connected", status: "met" },
      { id: "p2", description: "README explains the project", status: "met" },
      { id: "p3", description: "At least 10 commits during the commitment", target: 10, current: 8, unit: "commits", status: "progress" },
      { id: "p4", description: "Website is publicly accessible", status: "pending" },
      { id: "p5", description: "Main functionality can be demonstrated", status: "pending" },
    ],
    evidence: [],
    runs: [],
  },
  {
    id: "spanish",
    title: "Study Spanish for 20 hours",
    measurableGoal: "Log at least 20 hours of Spanish study between Sep 1 and Sep 30, 2026.",
    status: "passed",
    createdAt: "2026-09-01T08:00:00Z",
    lockedAt: "2026-09-01T08:03:00Z",
    deadline: "2026-09-30T23:59:00Z",
    stake: 50,
    currency: "USD",
    failureDestination: "Donate to Wikipedia",
    methods: ["data"],
    providers: ["google_calendar"],
    headline: { current: 21.4, target: 20, unit: "hours" },
    criteria: [
      { id: "s1", description: "At least 20 hours of tracked study sessions", target: 20, current: 21.4, unit: "hours", status: "met" },
    ],
    evidence: [],
    runs: [],
  },
  {
    id: "articles",
    title: "Publish 4 articles",
    measurableGoal: "Publish 4 original articles of 800+ words between Aug 1 and Aug 31, 2026.",
    status: "failed",
    createdAt: "2026-08-01T10:00:00Z",
    lockedAt: "2026-08-01T10:05:00Z",
    deadline: "2026-08-31T23:59:00Z",
    stake: 75,
    currency: "USD",
    failureDestination: "Donate to Electronic Frontier Foundation",
    methods: ["ai"],
    providers: [],
    headline: { current: 3, target: 4, unit: "articles" },
    criteria: [
      { id: "a1", description: "Article 1 published (800+ words)", status: "met" },
      { id: "a2", description: "Article 2 published (800+ words)", status: "met" },
      { id: "a3", description: "Article 3 published (800+ words)", status: "met" },
      { id: "a4", description: "Article 4 published (800+ words)", status: "failed" },
    ],
    evidence: [],
    runs: [],
  },
];

export const demoActivity: ActivityEvent[] = [
  { id: "e1", commitmentId: "portfolio", type: "progress", description: "GitHub detected commit #8 on alex/portfolio", at: "2026-10-07T01:20:00Z" },
  { id: "e2", commitmentId: "portfolio", type: "locked", description: "Commitment locked — “Ship my portfolio”", at: "2026-10-06T14:12:00Z" },
  { id: "e3", commitmentId: "portfolio", type: "rules_created", description: "5 success criteria defined for “Ship my portfolio”", at: "2026-10-06T14:10:00Z" },
  { id: "e4", commitmentId: "run-100", type: "progress", description: "72 km reached for “Run 100 km in October”", at: "2026-10-05T19:00:00Z" },
  { id: "e5", commitmentId: "spanish", type: "result", description: "Passed — $50 returned for “Study Spanish for 20 hours”", at: "2026-10-01T00:10:00Z" },
  { id: "e6", commitmentId: "run-100", type: "locked", description: "Commitment locked — “Run 100 km in October”", at: "2026-10-01T09:04:00Z" },
  { id: "e7", commitmentId: "articles", type: "result", description: "Failed — 3 / 4 verified, $75 consequence triggered", at: "2026-09-01T00:10:00Z" },
];
