import type { ActivityEvent, Commitment } from "./types";

export const DEMO_USER = { name: "Rodrigo", bio: "Builder · Data Engineer · Problem Solver", email: "", timezone: "America/Sao_Paulo", currency: "USD" };

function challenge(id: string, title: string, goal: string, rules: string[], evidence: string[], source: string, date: string, extra: Partial<Commitment> = {}): Commitment {
  const status = extra.status ?? "passed";
  const criteria = rules.map((description, i) => ({ id: `${id}-${i + 1}`, description, status: "met" as const }));
  const c: Commitment = {
    id, title, measurableGoal: goal, status, demo: true,
    createdAt: `${date}T09:00:00Z`, lockedAt: `${date}T09:00:00Z`, deadline: `${date}T23:59:00Z`,
    completedAt: status === "passed" ? `${date}T18:00:00Z` : undefined,
    stake: 0, currency: "USD", failureDestination: "Not specified in the original example",
    methods: ["referee"], providers: [], verificationSource: source, criteria,
    evidence: evidence.map((value, i) => ({ id: `${id}-e${i}`, criterionId: criteria[Math.min(i, criteria.length - 1)]?.id ?? "", type: "text", value: `Demo placeholder — ${value}`, submittedAt: `${date}T17:00:00Z` })),
    runs: [], ...extra,
  };
  c.runs = [{ id: `${id}-verification`, ranAt: `${date}T18:00:00Z`, verdicts: c.criteria.map((cr) => ({ criterionId: cr.id, status: cr.status === "met" ? "verified" : cr.status === "failed" ? "failed" : "insufficient_evidence", confidence: 1, reasoning: cr.status === "met" ? "Completed in the supplied demo scenario; supporting documents are placeholders." : cr.status === "failed" ? "Acceptance was not achieved in the supplied demo scenario." : "This milestone is not completed; no final verification yet.", evidenceUsed: c.evidence.filter((e) => e.criterionId === cr.id).map((e) => e.id) })) }];
  return c;
}

// Dates illustrate a personal timeline; real historical dates and documents were not supplied.
export const demoCommitments: Commitment[] = [
  challenge("projeto-rondon", "Projeto Rondon", "Create and conduct workshops for young people focused on culture, citizenship and technology.", ["Create workshops that address culture, citizenship and technology for the participating young people.", "Conduct at least one workshop with more than 120 young participants."], ["Workshop plan", "Event attendance record", "Activity documentation", "Photos / event material"], "Third-party / Event Evidence", "2024-07-20", { reflection: "Seeing more than 120 young people participate made the work feel real." }),
  challenge("liga-financeira", "Liga Financeira PUCRS", "Join the PUCRS financial market league and actively contribute to its intellectual activities.", ["Be accepted into the PUCRS financial market league.", "Create study groups.", "Contribute to articles or educational content."], ["Acceptance confirmation", "Study group records", "Published articles / content"], "Third-party evidence", "2024-11-30"),
  challenge("toninhathon", "ToninhaThon", "Create a viable project, compete successfully and advance it beyond the competition.", ["Create a viable project.", "Win the competition.", "Have the project selected for incubation by SEBRAE."], ["Project artifact", "Competition result", "SEBRAE incubation evidence"], "Competition result + incubation evidence", "2025-03-22"),
  challenge("pratham-books", "Pratham Books", "Be selected to participate, build a useful data engineering project with potential relevance for a platform serving 10 million users, and present the case.", ["Be selected.", "Build a useful data engineering project designed around a context serving approximately 10 million users.", "Present the case."], ["Selection evidence", "Project artifact", "Presentation evidence"], "Selection, project and presentation evidence", "2025-08-16", { contextMetric: { value: "10M", label: "potential users in the project context" } }),
  challenge("detectivesql", "detectiveSQL", "Create a SQL project that I personally find interesting enough to solve and make it available to other people.", ["Create something that I personally feel compelled to explore and solve.", "Publish and share it with other people."], ["Public project URL (not supplied)", "Repository / project evidence", "Public release / share evidence"], "Public project + release evidence", "2026-02-14", { reflection: "Built something I wanted to exist." }),
  challenge("torneio-empreendedor", "Torneio Empreendedor", "Develop and validate a technology project for healthcare, turn it into a real application and win the entrepreneurship competition.", ["Develop a project focused on healthcare.", "Validate the idea with a specialist.", "Win the competition.", "Develop the application with AGES.", "Win the final tournament."], ["Healthcare project artifact", "Expert validation", "Competition evidence", "AGES application evidence", "Final tournament result"], "Expert validation + competition + application evidence", "2026-06-20", { progression: ["Idea", "Expert validation", "Competition", "Product development", "Final tournament"] }),
  challenge("techfellow", "TechFellow", "Successfully complete the TechFellow application process and be accepted.", ["Apply.", "Prepare the application.", "Be accepted."], ["Application submission", "Prepared application", "Application outcome"], "Application process evidence", "2026-08-31", { status: "failed", criteria: [{ id: "techfellow-1", description: "Apply.", status: "met" }, { id: "techfellow-2", description: "Prepare the application.", status: "met" }, { id: "techfellow-3", description: "Be accepted.", status: "failed" }], reflection: "I completed the application, but didn't reach the final outcome." }),
  challenge("behring-founders", "Behring Founders", "Become a Behring Founder while taking the process seriously enough to deeply understand the organization and contribute value back to future applicants and founders.", [], ["Application submission", "Organization study notes", "Conversation with Bibi"], "Application + personal process evidence", "2026-10-01", { status: "active", completedAt: undefined, deadline: "2026-12-31T23:59:00Z", criteria: ["Submit the application.", "Study the organization, its philosophy, people and program in depth.", "Speak with Bibi.", "Advance to the in-person stage.", "Become a Behring Founder.", "Create something that returns value to future people going through the same path."].map((description, i) => ({ id: `behring-founders-${i + 1}`, description, status: i < 3 ? "met" : "pending" })) }),
];

export const demoActivity: ActivityEvent[] = demoCommitments.map((c): ActivityEvent => ({ id: `${c.id}-activity`, commitmentId: c.id, type: c.status === "active" ? "progress" : "result", description: `${c.title} — ${c.status === "passed" ? "completed (demo)" : c.status === "failed" ? "not completed · 2 / 3 criteria (demo)" : "3 / 6 milestones completed (demo)"}`, at: c.completedAt ?? c.createdAt })).sort((a, b) => b.at.localeCompare(a.at));
