/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppNewRouteImport } from './routes/app.new'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as RefereeTokenRouteImport } from './routes/referee.$token'
import { Route as AppCommitmentsIndexRouteImport } from './routes/app.commitments.index'
import { Route as AppTrophiesIndexRouteImport } from './routes/app.trophies.index'
import { Route as AppTrophiesIdRouteImport } from './routes/app.trophies.$id'
import { Route as AppCommitmentsIdIndexRouteImport } from './routes/app.commitments.$id.index'
import { Route as AppCommitmentsIdProofRouteImport } from './routes/app.commitments.$id.proof'
import { Route as AppCommitmentsIdResultRouteImport } from './routes/app.commitments.$id.result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const RefereeTokenRoute = RefereeTokenRouteImport.update({
  id: '/referee/$token',
  path: '/referee/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommitmentsIndexRoute = AppCommitmentsIndexRouteImport.update({
  id: '/commitments/',
  path: '/commitments/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrophiesIndexRoute = AppTrophiesIndexRouteImport.update({
  id: '/trophies/',
  path: '/trophies/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrophiesIdRoute = AppTrophiesIdRouteImport.update({
  id: '/trophies/$id',
  path: '/trophies/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCommitmentsIdIndexRoute = AppCommitmentsIdIndexRouteImport.update({
  id: '/commitments/$id/',
  path: '/commitments/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommitmentsIdProofRoute = AppCommitmentsIdProofRouteImport.update({
  id: '/commitments/$id/proof',
  path: '/commitments/$id/proof',
  getParentRoute: () => AppRoute,
} as any)
const AppCommitmentsIdResultRoute = AppCommitmentsIdResultRouteImport.update({
  id: '/commitments/$id/result',
  path: '/commitments/$id/result',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/activity': typeof AppActivityRoute
  '/app/new': typeof AppNewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/referee/$token': typeof RefereeTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/trophies/$id': typeof AppTrophiesIdRoute
  '/app/commitments/': typeof AppCommitmentsIndexRoute
  '/app/trophies/': typeof AppTrophiesIndexRoute
  '/app/commitments/$id/proof': typeof AppCommitmentsIdProofRoute
  '/app/commitments/$id/result': typeof AppCommitmentsIdResultRoute
  '/app/commitments/$id/': typeof AppCommitmentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/activity': typeof AppActivityRoute
  '/app/new': typeof AppNewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/referee/$token': typeof RefereeTokenRoute
  '/app': typeof AppIndexRoute
  '/app/trophies/$id': typeof AppTrophiesIdRoute
  '/app/commitments': typeof AppCommitmentsIndexRoute
  '/app/trophies': typeof AppTrophiesIndexRoute
  '/app/commitments/$id/proof': typeof AppCommitmentsIdProofRoute
  '/app/commitments/$id/result': typeof AppCommitmentsIdResultRoute
  '/app/commitments/$id': typeof AppCommitmentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/activity': typeof AppActivityRoute
  '/app/new': typeof AppNewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/referee/$token': typeof RefereeTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/trophies/$id': typeof AppTrophiesIdRoute
  '/app/commitments/': typeof AppCommitmentsIndexRoute
  '/app/trophies/': typeof AppTrophiesIndexRoute
  '/app/commitments/$id/proof': typeof AppCommitmentsIdProofRoute
  '/app/commitments/$id/result': typeof AppCommitmentsIdResultRoute
  '/app/commitments/$id/': typeof AppCommitmentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/activity'
    | '/app/new'
    | '/app/profile'
    | '/app/settings'
    | '/referee/$token'
    | '/app/'
    | '/app/trophies/$id'
    | '/app/commitments/'
    | '/app/trophies/'
    | '/app/commitments/$id/proof'
    | '/app/commitments/$id/result'
    | '/app/commitments/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/activity'
    | '/app/new'
    | '/app/profile'
    | '/app/settings'
    | '/referee/$token'
    | '/app'
    | '/app/trophies/$id'
    | '/app/commitments'
    | '/app/trophies'
    | '/app/commitments/$id/proof'
    | '/app/commitments/$id/result'
    | '/app/commitments/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/activity'
    | '/app/new'
    | '/app/profile'
    | '/app/settings'
    | '/referee/$token'
    | '/app/'
    | '/app/trophies/$id'
    | '/app/commitments/'
    | '/app/trophies/'
    | '/app/commitments/$id/proof'
    | '/app/commitments/$id/result'
    | '/app/commitments/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  RefereeTokenRoute: typeof RefereeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/referee/$token': {
      id: '/referee/$token'
      path: '/referee/$token'
      fullPath: '/referee/$token'
      preLoaderRoute: typeof RefereeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/commitments/': {
      id: '/app/commitments/'
      path: '/commitments'
      fullPath: '/app/commitments/'
      preLoaderRoute: typeof AppCommitmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trophies/': {
      id: '/app/trophies/'
      path: '/trophies'
      fullPath: '/app/trophies/'
      preLoaderRoute: typeof AppTrophiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trophies/$id': {
      id: '/app/trophies/$id'
      path: '/trophies/$id'
      fullPath: '/app/trophies/$id'
      preLoaderRoute: typeof AppTrophiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commitments/$id/': {
      id: '/app/commitments/$id/'
      path: '/commitments/$id'
      fullPath: '/app/commitments/$id/'
      preLoaderRoute: typeof AppCommitmentsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commitments/$id/proof': {
      id: '/app/commitments/$id/proof'
      path: '/commitments/$id/proof'
      fullPath: '/app/commitments/$id/proof'
      preLoaderRoute: typeof AppCommitmentsIdProofRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commitments/$id/result': {
      id: '/app/commitments/$id/result'
      path: '/commitments/$id/result'
      fullPath: '/app/commitments/$id/result'
      preLoaderRoute: typeof AppCommitmentsIdResultRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppNewRoute: typeof AppNewRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTrophiesIdRoute: typeof AppTrophiesIdRoute
  AppCommitmentsIndexRoute: typeof AppCommitmentsIndexRoute
  AppTrophiesIndexRoute: typeof AppTrophiesIndexRoute
  AppCommitmentsIdProofRoute: typeof AppCommitmentsIdProofRoute
  AppCommitmentsIdResultRoute: typeof AppCommitmentsIdResultRoute
  AppCommitmentsIdIndexRoute: typeof AppCommitmentsIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppNewRoute: AppNewRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppTrophiesIdRoute: AppTrophiesIdRoute,
  AppCommitmentsIndexRoute: AppCommitmentsIndexRoute,
  AppTrophiesIndexRoute: AppTrophiesIndexRoute,
  AppCommitmentsIdProofRoute: AppCommitmentsIdProofRoute,
  AppCommitmentsIdResultRoute: AppCommitmentsIdResultRoute,
  AppCommitmentsIdIndexRoute: AppCommitmentsIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  RefereeTokenRoute: RefereeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
